2021-10-11 09:41:30.859 | INFO     | uvicorn.server:serve:63 - Started server process [593]
2021-10-11 09:41:30.860 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 09:41:30.861 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 09:41:30.866 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 09:42:08.683 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4343/
2021-10-11 09:42:08.691 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/
2021-10-11 09:42:19.273 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4343/api
2021-10-11 09:42:19.275 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/api
2021-10-11 09:43:29.145 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4343/api
2021-10-11 09:43:29.148 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/api
2021-10-11 09:43:32.163 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 09:43:32.265 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 09:43:32.266 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 09:43:32.267 | INFO     | uvicorn.server:serve:73 - Finished server process [593]
2021-10-11 09:43:33.241 | INFO     | uvicorn.server:serve:63 - Started server process [1119]
2021-10-11 09:43:33.242 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 09:43:33.242 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 09:43:33.246 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 09:43:35.823 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4343/api
2021-10-11 09:43:35.829 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/api
2021-10-11 10:10:03.325 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 10:10:03.428 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 10:10:03.430 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 10:10:03.431 | INFO     | uvicorn.server:serve:73 - Finished server process [1119]
2021-10-11 10:12:36.084 | INFO     | uvicorn.server:serve:63 - Started server process [6451]
2021-10-11 10:12:36.085 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 10:12:36.086 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 10:12:36.089 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 10:12:48.726 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP POST for http://localhost:4343/predict
2021-10-11 10:12:48.728 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 422 for http://localhost:4343/predict
2021-10-11 10:18:46.532 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP POST for http://localhost:4343/predict
2021-10-11 10:18:46.533 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 422 for http://localhost:4343/predict
2021-10-11 10:19:17.517 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP POST for http://localhost:4343/predict
2021-10-11 10:19:17.518 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 422 for http://localhost:4343/predict
2021-10-11 10:20:27.956 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP POST for http://localhost:4343/predict
2021-10-11 10:20:27.959 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 422 for http://localhost:4343/predict
2021-10-11 10:20:39.366 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 10:20:39.467 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 10:20:39.468 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 10:20:39.469 | INFO     | uvicorn.server:serve:73 - Finished server process [6451]
2021-10-11 10:21:32.401 | INFO     | uvicorn.server:serve:63 - Started server process [8279]
2021-10-11 10:21:32.402 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 10:21:32.403 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 10:21:32.406 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 10:21:36.878 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP POST for http://localhost:4343/predict
2021-10-11 10:21:36.880 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 422 for http://localhost:4343/predict
2021-10-11 10:21:55.840 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP POST for http://localhost:4343/predict
2021-10-11 10:21:55.841 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 422 for http://localhost:4343/predict
2021-10-11 10:22:02.324 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 10:22:02.425 | INFO     | uvicorn.server:serve:73 - Finished server process [8279]
2021-10-11 10:22:03.453 | INFO     | uvicorn.server:serve:63 - Started server process [8465]
2021-10-11 10:22:03.454 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 10:22:03.454 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 10:22:03.458 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 10:22:06.712 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP POST for http://localhost:4343/predict
2021-10-11 10:22:06.716 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/predict
2021-10-11 10:22:33.684 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 10:22:33.785 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 10:22:33.786 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 10:22:33.787 | INFO     | uvicorn.server:serve:73 - Finished server process [8465]
2021-10-11 10:23:00.933 | INFO     | uvicorn.server:serve:63 - Started server process [8769]
2021-10-11 10:23:00.934 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 10:23:00.934 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 10:23:00.938 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 10:23:09.220 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP POST for http://localhost:4343/predict
2021-10-11 10:23:09.222 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/predict
2021-10-11 10:23:33.378 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 10:23:33.480 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 10:23:33.481 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 10:23:33.482 | INFO     | uvicorn.server:serve:73 - Finished server process [8769]
2021-10-11 10:23:34.309 | INFO     | uvicorn.server:serve:63 - Started server process [8950]
2021-10-11 10:23:34.310 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 10:23:34.311 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 10:23:34.317 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 10:23:42.332 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP POST for http://localhost:4343/predict
2021-10-11 10:23:42.334 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/predict
2021-10-11 10:23:55.709 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 10:23:55.811 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 10:23:55.811 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 10:23:55.812 | INFO     | uvicorn.server:serve:73 - Finished server process [8950]
2021-10-11 10:23:56.644 | INFO     | uvicorn.server:serve:63 - Started server process [9084]
2021-10-11 10:23:56.672 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 10:23:56.685 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 10:23:56.698 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 10:23:59.141 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP POST for http://localhost:4343/predict
2021-10-11 10:23:59.143 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/predict
2021-10-11 10:25:06.181 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP POST for http://localhost:4343/predict
2021-10-11 10:25:06.183 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/predict
2021-10-11 10:43:13.231 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 10:43:13.333 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 10:43:13.335 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 10:43:13.336 | INFO     | uvicorn.server:serve:73 - Finished server process [9084]
2021-10-11 10:45:18.674 | INFO     | uvicorn.server:serve:63 - Started server process [452]
2021-10-11 10:45:18.675 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 10:45:18.675 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 10:45:18.679 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4242 (Press CTRL+C to quit)
2021-10-11 10:45:32.236 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 10:45:32.338 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 10:45:32.340 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 10:45:32.341 | INFO     | uvicorn.server:serve:73 - Finished server process [452]
2021-10-11 10:45:43.515 | INFO     | uvicorn.server:serve:63 - Started server process [586]
2021-10-11 10:45:43.516 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 10:45:43.516 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 10:45:43.520 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 10:45:48.437 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP POST for http://localhost:4343/predict
2021-10-11 10:45:48.440 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/predict
2021-10-11 10:48:43.340 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 10:48:43.442 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 10:48:43.444 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 10:48:43.445 | INFO     | uvicorn.server:serve:73 - Finished server process [586]
2021-10-11 10:48:48.964 | INFO     | uvicorn.server:serve:63 - Started server process [1209]
2021-10-11 10:48:48.965 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 10:48:48.965 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 10:48:48.969 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 10:54:28.550 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 10:54:28.652 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 10:54:28.654 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 10:54:28.655 | INFO     | uvicorn.server:serve:73 - Finished server process [1209]
2021-10-11 10:54:46.674 | INFO     | uvicorn.server:serve:63 - Started server process [2359]
2021-10-11 10:54:46.675 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 10:54:46.676 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 10:54:46.681 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 12:30:05.221 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 12:30:05.325 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 12:30:05.331 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 12:30:05.333 | INFO     | uvicorn.server:serve:73 - Finished server process [2359]
2021-10-11 12:30:14.455 | INFO     | uvicorn.server:serve:63 - Started server process [12665]
2021-10-11 12:30:14.455 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 12:30:14.456 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 12:30:14.461 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 12:30:30.360 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP POST for http://localhost:4343/test
2021-10-11 12:30:30.363 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 405 for http://localhost:4343/test
2021-10-11 12:30:42.679 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 12:30:42.782 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 12:30:42.783 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 12:30:42.784 | INFO     | uvicorn.server:serve:73 - Finished server process [12665]
2021-10-11 12:30:46.945 | INFO     | uvicorn.server:serve:63 - Started server process [12841]
2021-10-11 12:30:46.948 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 12:30:46.949 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 12:30:46.953 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 12:30:49.318 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP POST for http://localhost:4343/test
2021-10-11 12:30:49.320 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 405 for http://localhost:4343/test
2021-10-11 12:30:56.373 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4343/test
2021-10-11 12:30:56.375 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/test
2021-10-11 12:33:09.921 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03&\xa5X\xc7\xa3\x81\xc6\xed1\x93\x81X\xe8d\x80\xd5\t\xfb5\xce\x8c\x8a:\x04Ox\xc4...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd891fa3a90>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891f6a430>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:09.941 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b"\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x1c\x06\x91p\x94\xf2]`0\xdb\xb4Uu\x8c|y\xb6I\rR\x7f\x01\xf7\xa9\xbc\\y\x9e9\xa...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd891fa3b80>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891f6a250>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:09.958 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03Y\xb9\xd9A\x1b\xba\xbb\x01\xedY\x81\xf1\xe9G9\xa2\xad\xe5\xfd\xe9mn\x8dL\x87\x1...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd891fa39a0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891f54d30>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:09.968 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b"\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x8a\x02\xbf\x0b\x10\xc4\xac\xd0\xc7\x83s\xdcX\x98\xd8GJ\xb9\xda?\xa4L|c_\x82\x...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd891fa38b0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891f54ee0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:11.024 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xd5\x138\x89\xe701"\x14\xcc7\x8a`}f-\xb8>G`\xa2\x00y\x9f\x0feT\xa5\x0f\xa2\xaf...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd891fa37c0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891fcdaf0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:11.030 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b"\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xc8!6\xb4\xfa\x90l\x99\xa8~\\\x19\xeeHT\xb8\xb2Z\xd7eRM\xd6-\x84\xd6\xf6@\xf6T...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd891fa34f0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891f54be0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:11.038 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xbd\n;\xb4(\xe4\xb3.\x1a\r\x06\x97\xfbw`\xee\xb0\xee\xc6\xe4\x8d\xc2.[\xd3\x9d...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd891fa3d60>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891f545b0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:11.042 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b"\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xf9\xed\xdd\x0e\x8e\x16\xc7\xbe\xb0'\xbe\xbfF\xea\x86)\x98V\x8a\xa3\x18\x12}\x...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd891fa3e50>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891f54c70>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:11.557 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b"\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xd4\xb2F\xf5\xb1\x00r\x05\xd4Q\t\x17\x8f#\x1e\xd1\xeb\tJY*\xbf\xe0\xd2\x87\xc0...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f604040>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891fcd760>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:11.562 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03Mb\xe4\xe6\xbd\xee\x19\xcda\x91\x07C\xf2\xa1\xdeI\x88\xf6Q\x1f\xa3\xb3\xa9\xdde...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f604130>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891f6a5e0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:11.574 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x8c\x96W}\x92+U\n<]\xbbu\x1f\xcb\x05g\xf9\x9f\xc2\x10`a\x08\xcd\xdd{\x8f\xb4]{...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f604220>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891f54460>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:11.580 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x84-[\xab>\xd5\x12Nv\x87Ft0\xb4O\xd4\xd6\xf1\xbd\xb3#\x96\x9cr\x1f[\x0c3\x1c\x...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f604310>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891f6adc0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:13.538 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xd9\xd9\xa0\x89\xa4\x81\xc5\xb8Pw\xb9\x9a@g\x04U\xca\x00k\xb7\x04\x1f\x8c\x07\...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f604400>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891f6a2e0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:13.546 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x035u\x8b$=\x8b\xf6H\xad\xc6\xda\x95q\xbd\x96\x96\x1e\xa7H\xb0Q2\xfc[-\xdb`T\xbf\x...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f6044f0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891f6a070>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:13.551 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xfe1\x90b\xdd\x06rL\t\xdeS&\xef*C~\xc55k.>\xde\xdd\xb9\x8a\x0b\xf82\x191Py bM\...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f6045e0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891f6af10>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:13.555 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03i\x01%?$\xfa\xf6\x1f\x0b\x91\xf8\xdc\xd5\ro8z\xdd\x14l \xf8\xddF\x929\x87\x7f\x...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f6046d0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891f6af40>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.019 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xa0J\x9e\xb4\xb9[h\x081\x95\x90B\x16\x16\x89^\x10^S\xe5\xefX\xae\xa9\x9d,\x91\...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f6047c0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891f6a0a0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.024 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xf3d\xa2rp\x8b}\x004J\x12\xa5\xfd\xc8\xef\x14\x8f\xa1\xdc\xd6\xcahS\xb8<R\xab\...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f6048b0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891f6a040>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.031 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03rBq\xae\xd6\xa0\xa58\xcf\x06\xbbS_\x1c\xa3\xa5\xda\x8f\x82i\xf5\x92\x9fF%F\xfb$...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f6049a0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f6221c0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.035 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03$\xdb\xaci\xbf\xd7J\xa0\xbdS|\xdb\xbeF\xe01`8w\x0c \x1f\x15\xe3c\xdd\x9a\x14\x8...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f604a90>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f6223d0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.235 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03c\x8bC\x86\xc7\x897\xa71\xad\n\xd2\\\xc8\xaf\x88h\xd1\xdf2,\xae\x9buwf\x7f\xe1\...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f604b80>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f6225e0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.242 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b"\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x89\xeeb\x97\xe3\xfb\x87\xb0<H\x84\xb5\xfc\x13\x9fV\x8bH\xb2\x99\xcf+o!\xb3\x8...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f604c70>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f6225b0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.247 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x039mR5#\xfc\xd2\xfa\xc1\xaa\x9cRX\xa9\xa2\xeb!$\xc9%\xe4\xf0\x99\xb3o\xfa\xf7\x93...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f604d60>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622700>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.251 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xdb\x86\xc5\xb8P*i\xf9H[9\xabtI\x89G\x99\xc90\xf7\xb6\x0f\x15+\x04\x81\xa5\x84...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f604e50>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622820>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.403 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x00\x92\xa8\x9bA\xb8\xc3q,\xc8rf\xdc\x1a\xf0G0\xb6r\x94H\r\x18\xe2I\xe8Cd\x8cC...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f626040>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622940>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.408 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x9f\x83M\xb3\xec\x0fY&\xda0t\xfc\xaf\x8c.\x1d\xda\xe9\x0c\xf78@\x14\xfa\x13jf\...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f626130>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622a60>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.413 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03E8\xfcy\x1c:\x0c\xcf\x88\xec\xa7^\xb8\xbd\x9a9\xfa\xe4 5\x1e\x84\n\xa1G\x88\xf7...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f626220>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622b80>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.418 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xaf\xb6\x95\x90\xd2\x85O\xb7\xd4\xa8\r\xa94\xceb\x05\xb4Z)yc\xe3\x8a\xdc\x9b\x...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f626310>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622ca0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.561 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xc4\x0eu}\x9e\xb3\x8d\x08\xe4\x84K\xe7`\xab\xd0\xc7Z\xec\xe5\x8a\n|\xfc\xd6\xa...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f626400>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd891f6afa0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.565 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xb6Zl\xcf\xb5 \x9c&"\xf6~N\x07/o\x17\x98\xb3c\xd1!\xa3\x8b\x9f\xe5\xf8$\r]\x01...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f6264f0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622ee0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.570 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x81\xce\x18\xea\x03\xdf\t=8Dz\xfc\x89\xe2\xfb\x18i\xcb\xd5/\xbf~Ue\xc5j\xda\xb...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f6265e0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622490>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.574 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x91YR\xd6\xd4[\xc3U\x96\x92B:J\x83^\x1b\xdc\xf2\xe0<\xba\xed\x12@\x99L\xa2N\x0...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f6266d0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f62a190>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.722 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x8d\x1fj\x8adA\xb8\xac\x989\xbbH\xeaF\xb6b\x16\xbe\x11v]\x87\xbb\xe1\xaf\xbc\x...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f6267c0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f62a340>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.727 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xbf\x15\xbcz\x00\xab\xb2\xf9\xa0\xbbw\xe8\xc0\x16,k\xf7y\xb4\x8a\x9d;#\x84\xd5...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f6268b0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f62a280>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.735 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x033\x1a\xeaJK\xfeQ\x19\xbe3\x9b\xd7\xb0\xf7-\xce\xabI0Y8\'\x82\x15SH\x9e\x08\xa7\...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd891fa3e50>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622e20>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.739 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x04\xe6k\xdc\x13\x82\x1dt\xdb\xfa(\x18r\xcd\xb1\x9f\x84C\xe0\x14\x96\xcepo\xe8...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd891fa3d60>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622d00>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.872 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xfc+\xfc\xb0\x04B\xd00\xdai^7H\xc3\x054\xc33\xab\xce\xcaw\x9b&=jp\xe9\xcf\x94\...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd891fa34f0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622dc0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.877 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xe9\xdfYgK\xc0\xedz2\x9eq\xb5\x9b\xe6\xf0\xa7\xe0\xe2\xe0z(\x0eS\x07\xef\x19\x...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd891fa37c0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622df0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.886 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xb1JA\x13\xbfUA1\xde\xa9B\xdc\xffQ\x19\xe2\xff\xeax\x9f\x18\xc47_\xf9\xf2\xee\...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd891fa38b0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622ac0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:14.893 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b"\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x04\xf6\xff\x8b\xe1\xb1\xbbG\xb5\x05\xb3\xac\xc9\xa7\xbd(\xf4\xde\xe8TUX\\\x97...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd891fa39a0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622bb0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:15.022 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03s\xc1\x8d\xec\xa3\x84\xc9\x15\x0b\xae\xcbcm\x1f\t0\x9f!|\xcf\xff\xe4i\x81\xc3e\...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f6269a0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f6229a0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:15.026 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xd5\xaff\x7f\xddj\xfd\xc9\xdf\x13t\\\x13\xfc\x8c\x9d\x88\x81\xaa\x95\xe4~&6\xd...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f6266d0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622760>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:15.031 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xab\xccS\xef|j\xe7\x7f\xb7\xd5\x19\x84\x844\x91\x16\xfc\x92\xee\xac\xd6\x1d\xd...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f6265e0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622610>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:15.035 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xad\xe2\\v0\x8e\xd1L%,\x9b\x10+\xc1\xfd\x05\xe8\xb9g\xf3\x823\xce\xb59\xc8\xdb...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f6264f0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622550>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:20.082 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xf4\x83\xb8\x82Z{\xa6\x13\xf08.\xc0$.=\x90\xfa\x94\x91\x08\x8f\x87\xcc\x10\xb4...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f626400>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f6222b0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:20.089 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03[rz&_3!a9\xb1\xbe\xd1,\xaa$<\x1b_\xd4\xde\xed+\xc0\x93\xa1\x19\xb9\x1b\xb3\x93c...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f626310>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622880>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:20.095 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xd4\x86\xd7\x83\xeb\x8e\xe3\xd5\xd3\x8d\xc6\xdc\x8d\x06\xbd\xfc\xdb\x88\xa6J\x...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f626220>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622040>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:20.100 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fd893a8eee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fd894711310>
    └ <uvicorn.server.Server object at 0x7fd892839df0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fd8947113a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fd892839df0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03zz\xf7\xc9\xf1\xdb\x04\x11T\xb9\xac\xffw\xd5\x93zH\xf6)\xb3J\xbet\x82l\r\x01t\x...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fd88f626130>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fd88f622190>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:29.055 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 12:33:29.156 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 12:33:29.158 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 12:33:29.160 | INFO     | uvicorn.server:serve:73 - Finished server process [12841]
2021-10-11 12:33:30.690 | INFO     | uvicorn.server:serve:63 - Started server process [13452]
2021-10-11 12:33:30.691 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 12:33:30.691 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 12:33:30.695 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 12:33:33.757 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fdc15381ee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fdc16004310>
    └ <uvicorn.server.Server object at 0x7fdc1412cdf0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fdc160043a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fdc1412cdf0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03q\xdem\x990\x0f\xcb\x0f\x19\xbb\xbd\r \xe4B\xc8A\xbd\xc3\x8b\xf8\xd7N),v.a\xf8\...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fdc138964f0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fdc138b2d30>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:33.769 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fdc15381ee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fdc16004310>
    └ <uvicorn.server.Server object at 0x7fdc1412cdf0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fdc160043a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fdc1412cdf0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03$\xd2\xe8G+\xa5\xb9\r\x86\x00"\x01\x97\xc8s,d\x08\xdd\xa3\x04\x91\xc3\x02\xfa\x...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fdc138967c0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fdc1413d6a0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:33.774 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fdc15381ee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fdc16004310>
    └ <uvicorn.server.Server object at 0x7fdc1412cdf0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fdc160043a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fdc1412cdf0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b"\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03f\xad2\xb8\xd1\xe9\xd0Mn\xd1\xd3uZ\x10\xdf\xbdv&'\xc53\x9c!\xd5\xbd&\x1c{\xc2\x...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fdc138969a0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fdc138c52b0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:33:33.779 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fdc15381ee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fdc16004310>
    └ <uvicorn.server.Server object at 0x7fdc1412cdf0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fdc160043a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fdc1412cdf0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xcb\xf4W\t\x83e\x13\x87\xb3\x94\x85\xcd\x9b\x87yt\x8a\xf2\xea\x89J\xac\x83\xdc...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fdc13896a90>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fdc138c53d0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:34:03.834 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fdc15381ee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fdc16004310>
    └ <uvicorn.server.Server object at 0x7fdc1412cdf0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fdc160043a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fdc1412cdf0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xe7\xb8\xb1[\xd07H\xca\xe55\xa6U\x96\xcfAoV9h\xd0\xa7:\x87\xc4\x13\xc5I\x9cT\x...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fdc13896b80>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fdc138c5d90>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:34:03.840 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fdc15381ee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fdc16004310>
    └ <uvicorn.server.Server object at 0x7fdc1412cdf0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fdc160043a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fdc1412cdf0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b"\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03oZ\xfd\xc9F\xc6\xa6H\xde]\xc7\x1d\xe0M\xf3R\x0b\x1c\x9f5\xb3f\x91-UGD&\x93\xe4\...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fdc13896c70>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fdc138c5f10>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:34:03.848 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fdc15381ee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fdc16004310>
    └ <uvicorn.server.Server object at 0x7fdc1412cdf0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fdc160043a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fdc1412cdf0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b"\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xb2\xad\x1a\x86\xc7H[m\x99\xf1\x0bh\xf6\x00\x06A8\xcb`TPY\x9fH%\xee\xeav:\xe6\...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fdc13896d60>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fdc138c5fa0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:34:03.852 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:168 - Invalid HTTP request received.Traceback (most recent call last):

  File "api.py", line 70, in <module>
    uvicorn.run(
    │       └ <function run at 0x7fdc15381ee0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fdc16004310>
    └ <uvicorn.server.Server object at 0x7fdc1412cdf0>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fdc160043a0>
    │    │                  └ <uvicorn.server.Server object at 0x7fdc1412cdf0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xc3a-\xe7n\x13\xd7\xb2\xc0b\x98Fu;\xdf\x1bR\xf3Wu\xac\xc0E\xbaIz\x83G1G]\xf0 \...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7fdc13896e50>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fdc1387c0a0>
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2021-10-11 12:34:45.337 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4343/test
2021-10-11 12:34:45.340 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/test
2021-10-11 12:34:45.417 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4343/favicon.ico
2021-10-11 12:34:45.421 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 404 for http://localhost:4343/favicon.ico
2021-10-11 12:35:05.296 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 12:35:05.399 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 12:35:05.401 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 12:35:05.402 | INFO     | uvicorn.server:serve:73 - Finished server process [13452]
2021-10-11 12:35:08.094 | INFO     | uvicorn.server:serve:63 - Started server process [13847]
2021-10-11 12:35:08.094 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 12:35:08.095 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 12:35:08.099 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 12:35:12.201 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4343/predict
2021-10-11 12:35:12.203 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/predict
2021-10-11 12:35:16.938 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 12:35:17.040 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 12:35:17.041 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 12:35:17.041 | INFO     | uvicorn.server:serve:73 - Finished server process [13847]
2021-10-11 12:36:18.509 | INFO     | uvicorn.server:serve:63 - Started server process [14134]
2021-10-11 12:36:18.510 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 12:36:18.510 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 12:36:18.514 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 12:36:19.171 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4343/test
2021-10-11 12:36:19.173 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/test
2021-10-11 12:36:22.204 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4343/test
2021-10-11 12:36:22.206 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/test
2021-10-11 12:37:29.428 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 12:37:29.530 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 12:37:29.532 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 12:37:29.533 | INFO     | uvicorn.server:serve:73 - Finished server process [14134]
2021-10-11 12:38:55.817 | INFO     | uvicorn.server:serve:63 - Started server process [411]
2021-10-11 12:38:55.817 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 12:38:55.818 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 12:38:55.822 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 12:39:09.782 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4343/test
2021-10-11 12:39:09.784 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/test
2021-10-11 12:39:12.953 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4343/test
2021-10-11 12:39:12.955 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/test
2021-10-11 12:40:13.640 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4343/test
2021-10-11 12:40:13.641 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/test
2021-10-11 12:43:12.390 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4343/test
2021-10-11 12:43:12.391 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/test
2021-10-11 12:50:56.843 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4343/test
2021-10-11 12:50:56.849 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/test
2021-10-11 12:51:13.187 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4343/test
2021-10-11 12:51:13.189 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/test
2021-10-11 13:09:05.926 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 13:09:06.029 | INFO     | uvicorn.server:serve:73 - Finished server process [411]
2021-10-11 13:12:00.565 | INFO     | uvicorn.server:serve:63 - Started server process [313]
2021-10-11 13:12:00.566 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 13:12:00.567 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 13:12:00.573 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4242 (Press CTRL+C to quit)
2021-10-11 13:12:32.054 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4243/
2021-10-11 13:12:32.055 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 404 for http://localhost:4243/
2021-10-11 13:12:32.128 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4243/favicon.ico
2021-10-11 13:12:32.129 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 404 for http://localhost:4243/favicon.ico
2021-10-11 13:12:37.821 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4243/
2021-10-11 13:12:37.823 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 404 for http://localhost:4243/
2021-10-11 13:12:55.090 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 13:12:55.192 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 13:12:55.192 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 13:12:55.193 | INFO     | uvicorn.server:serve:73 - Finished server process [313]
2021-10-11 13:13:03.642 | INFO     | uvicorn.server:serve:63 - Started server process [608]
2021-10-11 13:13:03.643 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 13:13:03.643 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 13:13:03.647 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4242 (Press CTRL+C to quit)
2021-10-11 13:13:20.821 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 13:13:20.924 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 13:13:20.925 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 13:13:20.926 | INFO     | uvicorn.server:serve:73 - Finished server process [608]
2021-10-11 13:13:21.678 | INFO     | uvicorn.server:serve:63 - Started server process [698]
2021-10-11 13:13:21.679 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 13:13:21.679 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 13:13:21.683 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 13:13:23.915 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4343/test
2021-10-11 13:13:23.917 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4343/test
2021-10-11 13:13:55.724 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 13:13:55.826 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 13:13:55.827 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 13:13:55.828 | INFO     | uvicorn.server:serve:73 - Finished server process [698]
2021-10-11 13:13:58.332 | INFO     | uvicorn.server:serve:63 - Started server process [863]
2021-10-11 13:13:58.333 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 13:13:58.333 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 13:13:58.337 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4343 (Press CTRL+C to quit)
2021-10-11 13:14:00.949 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 13:14:01.052 | INFO     | uvicorn.server:serve:73 - Finished server process [863]
2021-10-11 13:14:45.763 | INFO     | uvicorn.server:serve:63 - Started server process [335]
2021-10-11 13:14:45.764 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2021-10-11 13:14:45.764 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2021-10-11 13:14:45.769 | INFO     | uvicorn.server:startup:166 - Uvicorn running on http://0.0.0.0:4242 (Press CTRL+C to quit)
2021-10-11 13:14:53.505 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4242/test
2021-10-11 13:14:53.507 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 200 for http://localhost:4242/test
2021-10-11 13:14:58.008 | INFO     | utilities.logging.handlers:http_request_logging_middleware:36 - HTTP GET for http://localhost:4242/predict
2021-10-11 13:14:58.009 | INFO     | utilities.logging.handlers:http_request_logging_middleware:38 - HTTP 405 for http://localhost:4242/predict
2021-10-11 13:15:15.085 | INFO     | uvicorn.server:shutdown:209 - Shutting down
2021-10-11 13:15:15.187 | INFO     | uvicorn.lifespan.on:shutdown:43 - Waiting for application shutdown.
2021-10-11 13:15:15.188 | INFO     | uvicorn.lifespan.on:shutdown:46 - Application shutdown complete.
2021-10-11 13:15:15.188 | INFO     | uvicorn.server:serve:73 - Finished server process [335]
